{% set version = "2.1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-psych
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/psych_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/psych/psych_{{ version }}.tar.gz
  sha256: bd3b1676d15c7ff489ec8f5655e6712138c8a8220098cb4ec9098608b3e3bc66

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lattice
    - r-mnormt
    - r-nlme
  run:
    - r-base
    - r-lattice
    - r-mnormt
    - r-nlme

test:
  commands:
    - $R -e "library('psych')"           # [not win]
    - "\"%R%\" -e \"library('psych')\""  # [win]

about:
  home: https://personality-project.org/r/psych https://personality-project.org/r/psych-manual.pdf
  license: GPL-2.0-or-later
  summary: A general purpose toolbox for personality, psychometric theory and experimental psychology.   Functions are primarily for multivariate analysis and scale construction using factor analysis, principal component analysis, cluster analysis and reliability analysis, although others provide basic descriptive statistics.
    Item Response Theory is done using  factor analysis of tetrachoric and polychoric correlations. Functions for analyzing data at multiple levels include within and between group statistics, including correlations and factor analysis.   Functions for simulating and testing particular item and test structures are included.
    Several functions  serve as a useful front end for structural equation modeling.  Graphical displays of path diagrams, factor analysis and structural equation models are created using basic graphics. Some of the functions are written to support a book on psychometric theory as well as publications in personality research.
    For more information, see the <https://personality-project.org/r> web page.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: psych
# Version: 1.9.12
# Date: 2019-12-14
# Title: Procedures for Psychological, Psychometric, and Personality Research
# Authors@R: person("William", "Revelle", role =c("aut","cre"), email="revelle@northwestern.edu", comment=c(ORCID  = "0000-0003-4880-9610") )
# Description: A general purpose toolbox for personality, psychometric theory and experimental psychology.   Functions are primarily for multivariate analysis and scale construction using factor analysis, principal component analysis, cluster analysis and reliability analysis, although others provide basic descriptive statistics. Item Response Theory is done using  factor analysis of tetrachoric and polychoric correlations. Functions for analyzing data at multiple levels include within and between group statistics, including correlations and factor analysis.   Functions for simulating and testing particular item and test structures are included. Several functions  serve as a useful front end for structural equation modeling.  Graphical displays of path diagrams, factor analysis and structural equation models are created using basic graphics. Some of the functions are written to support a book on psychometric theory as well as publications in personality research. For more information, see the <https://personality-project.org/r> web page.
# License: GPL (>= 2)
# Imports: mnormt,parallel,stats,graphics,grDevices,methods,foreign,lattice,nlme
# Suggests: GPArotation, lavaan, sem, lme4,Rcsdp, graph, Rgraphviz,psychTools
# LazyData: yes
# ByteCompile: TRUE
# URL: https://personality-project.org/r/psych https://personality-project.org/r/psych-manual.pdf
# NeedsCompilation: no
# Packaged: 2019-12-15 20:23:29 UTC; WR
# Author: William Revelle [aut, cre] (<https://orcid.org/0000-0003-4880-9610>)
# Maintainer: William Revelle <revelle@northwestern.edu>
# Repository: CRAN
# Date/Publication: 2019-12-20 16:40:02 UTC
