travis:
  secure:
    BINSTAR_TOKEN: kZoaKE0w7dUOuLt003Lyb5na9pcwzKzz3IRZ93i1ZJrj30nTWgc7V6CVuMLz9GsJOPZ3K9d4gtiJSb4xol52P6xlPdrBoAtKVMqA/1Jt4d5I3vqzEX250OCCJDlq3geSt0eQLCCZJgO2ZE+j81mOTZFZJoXC09Q7hq0JUGvjvonrh0IsSGVyOQCzyPzJn4YOyE6MQ6Sfg7kUkou0FjVkljH1nZTOdiJ+7+dwHnlDOad+57NzCxTfDhsINYAIdHgsJCEAcvNhtY1K4iRR1dXys8WVFSEtXs8yw4H88E96WuQoIlWjUw4CZlZJwPno/yYlNx1Cz3LY1b/RB/lzhEFqgtq7W5TYdxvkvoUiGsmc9EKRhODAl9c+qO+CbvGK3M70kNK6moSUmKLustbiugPwlnfiNbLV0ouzEU4XnvZfdgu5ZPLR3Wwivfr5WOhkNXxhEzLs7zSCkL1/4LCl1Ym9pN7GQpPALicRDf13IaGHtrhGida3iqZyogOEX0n3sFgP57/+XGGFfRnMCNIpgxBOKcyuN+IPJynHRl8IsbHsdDGwgLZ4aVN+dTyZbietD1rugOGmaKrWLb5mUvPm7Ax0XG/7lof5ipdq+XsC/dQjo9GmSIHOq19qFh9Vl2bOTcMsWBmzA3UKy5aZ5x80TN63ClxZrdgU8XolMHzQlb/xzuo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
